# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CfH Tools
email: mrs.deanna.warren@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A consolidation of my quick and dirty tools. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fuzzy-sniffle.heroku.com" # the base hostname & protocol for your site
twitter_username: DeannaWarrenDev
github_username:  deannawarren

# Build settings
markdown: kramdown
